name: Transform Rules 
on:
  push:
    paths:
      - 'rules/**'

jobs:
  transform-rules:
    name: Transform rules content
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Transform rules
        id: transform
        uses: jpower432/trestle-bot/actions/rules-transform@bug/single-rule-failure
        with:
          rules_view_path: "rules/"
          file_pattern: "*.json,rules/*"