name: Transform Rules 
on:
  push:
    branches:
      - '!main'
    paths:
      - 'rules/**'

jobs:
  transform-rules:
    name: Transform rules content
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate app token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a
        id: get_installation_token
        with: 
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          permissions: >-
            {"contents": "write"}
      - name: Clone
        uses: actions/checkout@v3
        with:
          token: ${{ steps.get_installation_token.outputs.token }}
      - name: Transform rules
        id: transform
        uses: jpower432/trestle-bot/actions/rules-transform@bug/single-rule-failure
        with:
          rules_view_path: "rules/"
          file_pattern: "*.json,rules/*"
          commit_user_name: "trestle-bot[bot]"
          commit_user_email: "136850459+trestle-bot[bot]@users.noreply.github.com"